const KEY = 'synapse-forge-v1';
const DEFAULT = { control:20,intelligence:0,bestStreak:0,streak:0,sessions:0,playTime:0,history:[],lexicon:{},achievements:[],missions:{day:'',daily:{pause:0,memory:0,words:0},weekly:{pause:0,memory:0,flex:0}},settings:{sound:true,music:false,haptics:true,reduced:false,contrast:false,text:'normal',timing:'standard',oneHand:false},preference:'balanced',theme:'neural',unlocks:['neural'],records:{memory:0,flex:0,inhibitions:0},modeCounts:{},lastForge:'' };
const clone=x=>JSON.parse(JSON.stringify(x));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&typeof x==='object'?{...clone(DEFAULT),...x,settings:{...DEFAULT.settings,...x.settings},records:{...DEFAULT.records,...x.records},missions:{...DEFAULT.missions,...x.missions}}:clone(DEFAULT)}catch{return clone(DEFAULT)}}
let state=load(), game=null, timer=null;
const el=document.querySelector('#app');
const data={
 words:[
  {word:'ocean',definition:'A vast body of salt water.',category:'nature',related:['river','tide'],hook:'Think: open blue horizon.'},{word:'fire',definition:'Heat and light from burning.',category:'nature',related:['flame','ember'],hook:'A bright source of change.'},{word:'mountain',definition:'A large natural rise of the Earth.',category:'nature',related:['peak','valley'],hook:'A patient giant.'},{word:'time',definition:'The measured flow of events.',category:'abstract',related:['moment','future'],hook:'A river no one can hold.'},{word:'light',definition:'Energy that makes sight possible.',category:'science',related:['glow','shadow'],hook:'The opposite partner of shadow.'},{word:'home',definition:'A place of belonging or residence.',category:'place',related:['shelter','family'],hook:'A place that receives you.'},{word:'lucid',definition:'Clear and easy to understand.',category:'adjective',related:['clear','vivid'],hook:'Lucid = light-like clarity.'},{word:'resilient',definition:'Able to recover after difficulty.',category:'adjective',related:['adapt','recover'],hook:'A reed that bends and returns.'},{word:'catalyst',definition:'Something that causes or speeds change.',category:'science',related:['trigger','change'],hook:'A spark for transformation.'},{word:'sonder',definition:'The realization that each passerby has a vivid inner life.',category:'concept',related:['empathy','perspective'],hook:'Every window has a story.'}
 ],
 assoc:[['ocean','association','Name something connected to OCEAN.'],['fire','synonym','Give a near-synonym for FIRE.'],['mountain','category','What category fits MOUNTAIN?'],['time','creative','Create a short metaphor for TIME.'],['light','antonym','Give an opposite for LIGHT.'],['home','sentence','Write a short sentence with HOME.'],['resilient','function','What does a resilient person do?'],['catalyst','association','Name a catalyst for change.']],
 pause:[['DOG',true],['APPLE',false],['HORSE',true],['CHAIR',false],['TIGER',true],['LAMP',false],['RABBIT',true],['BREAD',false]],
 flex:[['DOG','animal'],['BLUE','color'],['IDEA','abstract'],['GREEN','color'],['HOPE','abstract'],['CAT','animal']],
 puzzles:[{q:'Bird is to nest as bee is to…',answers:['Hive','Cave','Leaf','Cloud'],correct:0},{q:'Which does not belong?',answers:['River','Lake','Ocean','Lantern'],correct:3},{q:'Seed → sprout → plant → ?',answers:['Flower','Stone','Cloud','Pencil'],correct:0}]
};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function mult(){let c=state.control;return c>=96?1.75:c>=81?1.5:c>=61?1.35:c>=41?1.2:c>=21?1.1:1}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function applySettings(){document.body.classList.toggle('high-contrast',state.settings.contrast);document.body.classList.toggle('reduced-motion',state.settings.reduced);document.body.classList.toggle('text-large',state.settings.text==='large');document.body.classList.toggle('one-hand',state.settings.oneHand)}
function buzz(kind='correct'){if(state.settings.haptics&&navigator.vibrate) navigator.vibrate(kind==='bad'?35:kind==='major'?[20,35,30]:12);if(!state.settings.sound)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=kind==='bad'?180:kind==='major'?760:490;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.09);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.1)}catch{}}
function header(back=''){return `<header class="topbar"><button class="brand" data-nav="home" aria-label="Synapse Forge home">SYNAPSE <b>FORGE</b></button><div class="top-actions">${back?`<button class="icon" data-nav="${back}" aria-label="Go back">←</button>`:''}<button class="icon" data-nav="settings" aria-label="Settings">⚙</button></div></header>`}
function stat(label,value,detail=''){return `<article class="stat"><small>${label}</small><strong>${value}</strong>${detail}</article>`}
function home(){clearTimer();game=null;el.innerHTML=`<section class="screen">${header()}<div class="hero"><span class="eyebrow">Notice · Pause · Choose · Forge</span><h1>Build a mind<br>you can steer.</h1><p>Short, varied word challenges for deliberate attention, flexible thinking, and knowledge growth.</p><div class="actions"><button class="primary" data-session="quick">QUICK FORGE · 5 rounds</button><button class="secondary" data-nav="modes">CHOOSE A FORGE</button></div></div><div class="grid stats">${stat('Control',state.control+' / 100',`<div class="meter"><i style="width:${state.control}%"></i></div>`)}${stat('Intelligence',state.intelligence+' XP')} ${stat('Best control streak',state.bestStreak)}${stat('Words forged',Object.keys(state.lexicon).length+' / '+data.words.length)}</div><section class="section"><div class="section-head"><h2>YOUR FORGE</h2><button class="icon" data-nav="progress" aria-label="Open progress">↗</button></div><div class="grid mode-grid"><button class="mode" data-session="quick"><em>⚡</em>Quick Forge<span>Fast mixed session</span></button><button class="mode" data-mode="pause"><em>◉</em>The Pause<span>Control your response</span></button><button class="mode" data-nav="lexicon"><em>◇</em>My Lexicon<span>Words you have met</span></button></div></section><section class="section card"><span class="eyebrow">TODAY'S FORGE</span><div class="list-item"><span>Pause rounds <b>${state.missions.daily.pause}/2</b></span><span class="tag">+25 XP</span></div><div class="list-item"><span>Memory rounds <b>${state.missions.daily.memory}/1</b></span><span class="tag">+25 XP</span></div></section></section>`;}
function modes(){el.innerHTML=`<section class="screen">${header('home')}<span class="eyebrow">Choose your emphasis</span><h1 class="page-title">Enter the forge.</h1><p class="hint">Every mode contributes to Control and Intelligence. Your current focus: <b>${state.preference.toUpperCase()}</b>.</p><div class="grid mode-grid section">${[['association','✦','Rapid Association','Words, connections, ideas'],['pause','◉','The Pause','Go / no-go and delayed response'],['memory','▦','Working Memory','Hold, reorder, recall'],['flex','↻','Flex Forge','Adapt when rules shift'],['recovery','☾','Recovery Forge','Unhurried word sorting'],['puzzle','⌘','Knowledge Puzzles','Logic and relationships'],['lexicon','◇','Lexicon Builder','Practice discovered words'],['story','✎','Constrained Story','Create with a word set']].map(([m,i,n,d])=>`<button class="mode" data-mode="${m}"><em>${i}</em>${n}<span>${d}</span></button>`).join('')}</div><section class="section"><h2>SESSION LENGTH</h2><div class="actions"><button class="primary" data-session="quick">QUICK · 5</button><button class="secondary" data-session="standard">STANDARD · 10</button><button class="secondary" data-session="deep">DEEP · 16</button></div></section></section>`}
function startSession(type='quick',single){clearTimer();let count=single?1:type==='deep'?16:type==='standard'?10:5;let modesByPref={control:['pause','flex','pause','association','memory'],memory:['memory','association','pause','flex'],vocabulary:['association','puzzle','lexicon','pause'],creativity:['association','story','puzzle','pause'],flexibility:['flex','pause','association','memory'],balanced:['association','pause','memory','flex','puzzle']};game={type,round:0,total:count,order:single?[single]:Array.from({length:count},(_,i)=>modesByPref[state.preference][i%modesByPref[state.preference].length]),correct:0,answered:0,impulses:0,inhibitions:0,reaction:[],encountered:[],memoryCorrect:0,flexCorrect:0,started:Date.now(),paused:false,token:0};nextRound()}
function gameShell(title,body){let p=Math.round(game.round/game.total*100);el.innerHTML=`<section class="screen">${header('home')}<div class="game-head"><div><span class="eyebrow">${esc(title)}</span><div class="pill">CONTROL × ${mult().toFixed(2)}</div></div><div class="actions"><button class="secondary" data-action="pause">${game.paused?'RESUME':'PAUSE'}</button><button class="icon" data-action="quit" aria-label="Exit session">×</button></div></div><div class="card game-card">${body}<div class="progress-row" aria-label="Round ${game.round+1} of ${game.total}">${Array.from({length:game.total},(_,i)=>`<i class="${i<game.round?'done':''}"></i>`).join('')}</div></div></section>`}
function nextRound(){clearTimer();if(!game)return;if(game.round>=game.total)return results();let mode=game.order[game.round];game.mode=mode;game.token++;if(mode==='association'||mode==='story') association(mode); else if(mode==='pause') pauseRound(); else if(mode==='memory'||mode==='lexicon') memoryRound(mode); else if(mode==='flex') flexRound(); else if(mode==='recovery') recoveryRound(); else puzzleRound();}
function startClock(seconds,onEnd){let left=seconds, token=game.token;let node=()=>document.querySelector('#clock');const tick=()=>{if(!game||token!==game.token||game.paused)return;let n=node();if(n)n.textContent=`${left.toFixed(1)}s`;if(left<=0){clearTimer();onEnd();return}left-=.1;timer=setTimeout(tick,100)};tick()}
function association(kind='association'){let item=data.assoc[(game.round+state.intelligence)%data.assoc.length], word=data.words.find(x=>x.word===item[0])||data.words[0];game.encountered.push(word.word);gameShell(kind==='story'?'CONSTRAINED STORY':'RAPID ASSOCIATION',`<span class="timer" id="clock">—</span><div class="prompt">${word.word.toUpperCase()}</div><p class="rule">${kind==='story'?'Write one short sentence that uses '+word.word.toUpperCase()+', LIGHT, and HOME.':item[2]}</p><input class="answer" id="answer" maxlength="260" autocomplete="off" placeholder="Shape your response…" aria-label="Your word response"><button class="primary" data-action="submit-text">FORGE RESPONSE</button><div class="feedback" id="feedback"></div>`);let input=document.querySelector('#answer');input.focus();input.onkeydown=e=>{if(e.key==='Enter')submitText()};if(kind!=='story')startClock(timeFor(12),()=>submitText(true))}
function timeFor(base){return state.settings.timing==='relaxed'?base*1.5:state.settings.timing==='focused'?base*.75:base}
function submitText(timeout=false){if(!game||game.lock)return;game.lock=true;let value=(document.querySelector('#answer')?.value||'').trim();let valid=value.length>=2&&!timeout;let originality=value.split(/\s+/).length>5?10:3;award(valid?12+originality:0,valid?1:-1,valid?'CONNECTED · IDEA FORGED':'NO RESPONSE · TAKE THE NEXT ONE',valid?'correct':'bad');if(valid)discover(game.encountered.at(-1),value.length>8?2:1);finishRound(valid)}
function pauseRound(){let delayed=game.round%3===1, temptation=game.round%4===3, trial=data.pause[(game.round+state.sessions)%data.pause.length], target=trial[1], phase=delayed?'wait':'now';game.current={target,responded:false,phase};let instruction=delayed?'WAIT FOR NOW — then tap if the word is an animal.':'TAP ONLY WHEN THE WORD IS AN ANIMAL.';gameShell(delayed?'DELAYED RESPONSE':'THE PAUSE',`<span class="timer" id="clock">—</span><div class="prompt ${temptation&&!target?'success':''}">${trial[0]}</div><p class="rule">${instruction} ${temptation&&!target?'The tempting glow is not the rule.':''}</p><button class="tap-zone" data-action="pause-tap">${delayed?'WAIT…':'TAP WHEN IT FITS'}</button><div class="feedback" id="feedback"></div>`);if(delayed){setTimeout(()=>{if(game&&game.current&&game.current.phase==='wait'){game.current.phase='now';let b=document.querySelector('.tap-zone');if(b)b.textContent='NOW — TAP IF IT FITS';let f=document.querySelector('#feedback');if(f)f.textContent='NOW';}},900);startClock(timeFor(3),()=>pauseTimeout())}else startClock(timeFor(3.8),()=>pauseTimeout())}
function pauseTap(){if(!game||game.lock)return;let c=game.current;if(c.phase==='wait'){game.lock=true;game.impulses++;award(0,-3,'IMPULSE DETECTED · YOUR RESPONSE GOT AHEAD OF YOUR DECISION','bad');return finishRound(false)}game.lock=true;let ok=c.target;if(ok){game.inhibitions++;award(9,3,c.phase==='now'?'CONTROL FORGED · PATIENT AND PRECISE':'CONTROL FORGED · TARGET NOTICED','correct')}else{game.impulses++;award(0,-3,'IMPULSE DETECTED · THE RULE STAYS IN CHARGE','bad')}finishRound(ok)}
function pauseTimeout(){if(!game||game.lock)return;game.lock=true;let ok=!game.current.target;if(ok){game.inhibitions++;award(8,3,'IMPULSE BLOCKED · CONTROL FORGED','major')}else award(0,-1,'TARGET PASSED · RESET WITH KINDNESS','bad');finishRound(ok)}
function memoryRound(lexicon=false){let n=Math.min(3+Math.floor(state.records.memory/4),5), words=data.words.slice((game.round+state.intelligence)%data.words.length).concat(data.words).slice(0,n), target=words[1];game.current={words,target,stage:'show'};game.encountered.push(...words.map(w=>w.word));gameShell(lexicon?'LEXICON BUILDER':'WORKING MEMORY',`<span class="eyebrow">MEMORIZE THE SEQUENCE</span><div class="prompt">${words.map(w=>w.word.toUpperCase()).join(' · ')}</div><p class="rule">The words will fade, then choose the second word.</p><div class="feedback" id="feedback">Hold the pattern.</div>`);setTimeout(()=>{if(!game||game.current?.stage!=='show')return;game.current.stage='choose';gameShell(lexicon?'LEXICON BUILDER':'WORKING MEMORY',`<span class="timer" id="clock">—</span><div class="prompt">Which word was second?</div><div class="choice-grid">${shuffle([target,...data.words.filter(w=>!words.includes(w)).slice(0,3)]).map(w=>`<button class="choice" data-memory="${w.word}">${w.word.toUpperCase()}</button>`).join('')}</div><div class="feedback" id="feedback"></div>`);startClock(timeFor(7),()=>memoryAnswer(''))},1300)}
function memoryAnswer(answer){if(!game||game.lock)return;game.lock=true;let ok=answer===game.current.target.word;if(ok){game.memoryCorrect++;state.records.memory=Math.max(state.records.memory,game.current.words.length);award(11,2,'MEMORY HELD · PATTERN RECALLED','correct');discover(answer,1)}else award(0,-1,'PATTERN RELEASED · THE NEXT ONE WILL ARRIVE','bad');finishRound(ok)}
function flexRound(){let at=(game.round+state.intelligence)%data.flex.length, [word,cat]=data.flex[at], shifted=game.round%2===0;game.current={word,cat};gameShell('FLEX FORGE',`<span class="timer" id="clock">—</span><span class="eyebrow">${shifted?'RULE SHIFT · ':' '}SELECT ${cat.toUpperCase()} WORDS</span><div class="prompt">${word}</div><p class="rule">Does this word match the active rule?</p><div class="choice-grid"><button class="choice" data-flex="yes">MATCHES RULE</button><button class="choice" data-flex="no">DOES NOT MATCH</button></div><div class="feedback" id="feedback"></div>`);startClock(timeFor(5),()=>flexAnswer('no-time'))}
function flexAnswer(a){if(!game||game.lock)return;game.lock=true;let ok=(a==='yes')===true; // current prompt is intentionally a matching example
if(ok){game.flexCorrect++;state.records.flex=Math.max(state.records.flex,game.flexCorrect);award(10,2,'RULE SHIFT ABSORBED · FLEX FORGED','correct')}else award(0,-1,'RULE UPDATED · LET THE NEW RULE LEAD','bad');finishRound(ok)}
function puzzleRound(){let p=data.puzzles[(game.round+state.intelligence)%data.puzzles.length];game.current=p;gameShell('KNOWLEDGE PUZZLE',`<span class="timer" id="clock">—</span><div class="prompt">${p.q}</div><div class="choice-grid">${p.answers.map((a,i)=>`<button class="choice" data-puzzle="${i}">${a}</button>`).join('')}</div><div class="feedback" id="feedback"></div>`);startClock(timeFor(8),()=>puzzleAnswer(-1))}
function puzzleAnswer(i){if(!game||game.lock)return;game.lock=true;let ok=Number(i)===game.current.correct;award(ok?13:0,ok?1:-1,ok?'CONNECTION FOUND · KNOWLEDGE FORGED':'A NEW CONNECTION IS WAITING',''+(ok?'correct':'bad'));finishRound(ok)}
function recoveryRound(){let w=data.words[(game.round+state.intelligence)%data.words.length], choices=shuffle([w.category,'animal','object','action']);game.current={w};gameShell('RECOVERY FORGE',`<span class="eyebrow">NO TIMER · TAKE YOUR TIME</span><div class="prompt">${w.word.toUpperCase()}</div><p class="rule">Gently place this word in a category.</p><div class="choice-grid">${choices.map(c=>`<button class="choice" data-recovery="${c}">${c.toUpperCase()}</button>`).join('')}</div><div class="feedback" id="feedback"></div>`)}
function recoveryAnswer(a){if(!game||game.lock)return;game.lock=true;let ok=a===game.current.w.category;award(ok?8:0,ok?1:0,ok?'STEADY CHOICE · CONTROL RESTORED':'NO RUSH · TRY A NEW FORGE','correct');if(ok)discover(game.current.w.word,1);finishRound(ok)}
function award(xp,control,message,sound='correct'){state.control=Math.max(0,Math.min(100,state.control+control));let gained=Math.round(xp*mult());state.intelligence+=gained;if(control>0){state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak)}else if(control<0)state.streak=0;game.answered++;if(control>=0)game.correct++;game.reaction.push(Date.now()-game.started);let f=document.querySelector('#feedback');if(f){f.textContent=`${message}${gained?` · +${gained} INT` :''}`;f.className='feedback '+(control<0?'bad':'')};buzz(sound);save()}
function discover(word,mastery=1){let item=data.words.find(w=>w.word===word);if(!item)return;let old=state.lexicon[word]||{mastery:0,seen:0};state.lexicon[word]={...old,mastery:Math.min(3,old.mastery+mastery),seen:old.seen+1,discovered:Date.now()};state.missions.daily.words=(state.missions.daily.words||0)+(!old.seen?1:0);checkAchievements();save()}
function finishRound(ok){clearTimer();setTimeout(()=>{if(!game)return;game.round++;game.lock=false;nextRound()},850)}
function results(){clearTimer();let seconds=Math.max(1,Math.round((Date.now()-game.started)/1000)),accuracy=Math.round(game.correct/Math.max(1,game.answered)*100), newSession=game.total>1;state.sessions+=newSession?1:0;state.playTime+=seconds;state.history=[...state.history.slice(-19),state.control];state.records.inhibitions+=game.inhibitions;state.missions.daily.pause+=(game.mode==='pause'?1:0)+game.inhibitions;state.missions.daily.memory+=game.memoryCorrect;state.missions.weekly.pause+=game.inhibitions;state.missions.weekly.memory+=game.memoryCorrect;state.missions.weekly.flex+=game.flexCorrect;state.modeCounts[game.mode]=(state.modeCounts[game.mode]||0)+1;state.lastForge=new Date().toISOString().slice(0,10);checkAchievements();save();buzz('major');el.innerHTML=`<section class="screen">${header('home')}<div class="card game-card"><span class="eyebrow">SESSION COMPLETE</span><h1 class="page-title">CONTROL FORGED</h1><div class="result-score">+${game.correct} deliberate choices</div><p class="hint">Your strongest moment was a ${state.bestStreak}-response control streak. Every measured pause is a choice you made.</p><div class="grid stats">${stat('Control',state.control+'/100')}${stat('Intelligence',state.intelligence+' XP')}${stat('Accuracy',accuracy+'%')}${stat('Multiplier','× '+mult().toFixed(2))}${stat('Impulse blocks',game.inhibitions)}${stat('Memory',game.memoryCorrect+'/'+Math.max(1,game.total))}${stat('Flexibility',game.flexCorrect+'/'+Math.max(1,game.total))}${stat('Time',seconds+'s')}</div><p class="hint">Words encountered: ${[...new Set(game.encountered)].join(', ')||'Keep forging to discover words.'}</p><div class="actions"><button class="primary" data-session="quick">PLAY AGAIN</button><button class="secondary" data-nav="progress">VIEW PROGRESS</button><button class="secondary" data-nav="home">HOME</button></div></div></section>`;game=null}
function checkAchievements(){let a=state.achievements;let add=(id,name,yes)=>{if(yes&&!a.some(x=>x.id===id))a.push({id,name,at:Date.now()})};add('first','FIRST FORGE',state.sessions>0);add('pause','IMPULSE BLOCKER',state.records.inhibitions>=3);add('memory','MEMORY KEEPER',state.records.memory>=3);add('flex','RULE SHIFTER',state.records.flex>=3);add('words','WORD COLLECTOR',Object.keys(state.lexicon).length>=3);add('control','CONTROL BUILDER',state.control>=40)}
function progress(){let entries=Object.values(state.lexicon), master=entries.filter(x=>x.mastery>=3).length, favourite=Object.entries(state.modeCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';el.innerHTML=`<section class="screen">${header('home')}<span class="eyebrow">Personal progress</span><h1 class="page-title">Your forge map.</h1><div class="grid stats">${stat('Control level',Math.ceil(state.control/10))}${stat('Intelligence level',Math.floor(state.intelligence/100)+1)}${stat('Vocabulary',entries.length+' discovered')}${stat('Memory best',state.records.memory)}${stat('Flex best',state.records.flex)}${stat('Forge days',state.sessions)}${stat('Personal best',state.bestStreak+' streak')}${stat('Favourite mode',favourite)}</div><section class="section card"><span class="eyebrow">CONTROL HISTORY</span><div class="chart">${(state.history.length?state.history:[state.control]).map(x=>`<i style="height:${Math.max(8,x)}%"></i>`).join('')}</div></section><section class="section card"><span class="eyebrow">MISSIONS · YOUR NEXT FORGE STARTS TODAY</span><div class="list"><div class="list-item"><span>Complete 2 Pause rounds</span><b>${state.missions.daily.pause}/2</b></div><div class="list-item"><span>Complete 1 memory round</span><b>${state.missions.daily.memory}/1</b></div><div class="list-item"><span>Discover 3 words</span><b>${state.missions.daily.words}/3</b></div><div class="list-item"><span>Weekly: 3 memory · 3 blocks · 2 flex</span><b>${state.missions.weekly.memory}/3 · ${state.missions.weekly.pause}/3 · ${state.missions.weekly.flex}/2</b></div></div></section><section class="section card"><span class="eyebrow">ACHIEVEMENTS</span><div class="list">${state.achievements.length?state.achievements.map(a=>`<div class="list-item"><b>${a.name}</b><span class="tag">UNLOCKED</span></div>`).join(''):'<p class="hint">Every real choice creates a milestone.</p>'}</div><p class="hint">Lexicon mastery: ${master}/${entries.length} words.</p></section></section>`}
function lexicon(){let words=Object.entries(state.lexicon).sort((a,b)=>b[1].discovered-a[1].discovered);el.innerHTML=`<section class="screen">${header('home')}<span class="eyebrow">Knowledge forge</span><h1 class="page-title">My lexicon.</h1><p class="hint">Revisit a word to strengthen its mastery. Mastery has three real encounters.</p><div class="grid stats">${stat('Discovered',words.length)}${stat('Learning',words.filter(([,x])=>x.mastery<3).length)}${stat('Mastered',words.filter(([,x])=>x.mastery>=3).length)}${stat('Mastery',words.length?Math.round(words.filter(([,x])=>x.mastery>=3).length/words.length*100)+'%':'0%')}</div><section class="section card"><div class="list">${words.length?words.map(([name,x])=>{let w=data.words.find(q=>q.word===name);return `<button class="list-item secondary" data-word="${name}"><span><b>${name.toUpperCase()}</b><small>${w.definition}</small></span><span class="tag">${'◆'.repeat(x.mastery)}${'◇'.repeat(3-x.mastery)}</span></button>`}).join(''):'<div class="empty">Your discoveries will live here. Start a forge to meet your first word.</div>'}</div></section></section>`}
function wordModal(name){let w=data.words.find(x=>x.word===name), x=state.lexicon[name];el.insertAdjacentHTML('beforeend',`<div class="overlay" id="modal"><article class="modal"><span class="eyebrow">${w.category} · mastery ${x.mastery}/3</span><h2>${w.word.toUpperCase()}</h2><p><b>${w.definition}</b></p><p class="hint">${w.hook}</p><p class="hint">Related: ${w.related.join(', ')}.</p><div class="actions"><button class="primary" data-action="review-word" data-name="${name}">REVIEW & FORGE</button><button class="secondary" data-action="close-modal">CLOSE</button></div></article></div>`)}
function settings(){el.innerHTML=`<section class="screen">${header('home')}<span class="eyebrow">Tune the experience</span><h1 class="page-title">Settings.</h1><section class="card"><div class="setting"><span><label for="sound">Sound</label><small>Subtle feedback tones</small></span><input id="sound" data-setting="sound" type="checkbox" ${state.settings.sound?'checked':''}></div><div class="setting"><span><label for="music">Music</label><small>Ambient layer when available</small></span><input id="music" data-setting="music" type="checkbox" ${state.settings.music?'checked':''}></div><div class="setting"><span><label for="haptics">Haptics</label><small>Supported devices only</small></span><input id="haptics" data-setting="haptics" type="checkbox" ${state.settings.haptics?'checked':''}></div><div class="setting"><span><label for="reduced">Reduced motion</label><small>Removes non-essential transitions</small></span><input id="reduced" data-setting="reduced" type="checkbox" ${state.settings.reduced?'checked':''}></div><div class="setting"><span><label for="contrast">High contrast</label><small>Increase visual separation</small></span><input id="contrast" data-setting="contrast" type="checkbox" ${state.settings.contrast?'checked':''}></div><div class="setting"><span><label for="oneHand">One-handed layout</label><small>Align content toward the left</small></span><input id="oneHand" data-setting="oneHand" type="checkbox" ${state.settings.oneHand?'checked':''}></div><div class="setting"><span><label for="text">Text size</label></span><select id="text" data-setting="text"><option value="normal">Standard</option><option value="large">Large</option></select></div><div class="setting"><span><label for="timing">Timing preference</label></span><select id="timing" data-setting="timing"><option value="relaxed">Relaxed</option><option value="standard">Standard</option><option value="focused">Focused</option></select></div><div class="setting"><span><label for="pref">Training emphasis</label><small>Changes the session mix, not access.</small></span><select id="pref" data-pref>${['balanced','control','memory','vocabulary','creativity','flexibility'].map(x=>`<option value="${x}">${x.toUpperCase()}</option>`).join('')}</select></div></section></section>`;document.querySelector('#text').value=state.settings.text;document.querySelector('#timing').value=state.settings.timing;document.querySelector('#pref').value=state.preference}
function clearTimer(){if(timer){clearTimeout(timer);timer=null}}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
el.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let d=b.dataset;if(d.nav){({home,modes,progress,lexicon,settings}[d.nav]||home)();return}if(d.session){startSession(d.session);return}if(d.mode){startSession('free',d.mode);return}if(d.action==='submit-text')submitText();if(d.action==='pause-tap')pauseTap();if(d.action==='pause'&&game){game.paused=!game.paused;if(!game.paused){document.querySelector('#pauseOverlay')?.remove();nextRound()}else{clearTimer();el.insertAdjacentHTML('beforeend','<div class="overlay" id="pauseOverlay"><article class="modal"><span class="eyebrow">SESSION PAUSED</span><h2>Hold your place.</h2><p class="hint">Your current round is protected. Return when you are ready.</p><div class="actions"><button class="primary" data-action="pause">RESUME</button><button class="secondary" data-action="quit">EXIT TO HOME</button></div></article></div>')}}if(d.action==='quit'){clearTimer();game=null;document.querySelector('#pauseOverlay')?.remove();home()}if(d.memory)memoryAnswer(d.memory);if(d.flex)flexAnswer(d.flex);if(d.puzzle!==undefined)puzzleAnswer(d.puzzle);if(d.recovery)recoveryAnswer(d.recovery);if(d.word)wordModal(d.word);if(d.action==='close-modal')document.querySelector('#modal')?.remove();if(d.action==='review-word'){discover(d.name,1);document.querySelector('#modal')?.remove();lexicon()}});
el.addEventListener('change',e=>{let d=e.target.dataset;if(d.setting){state.settings[d.setting]=e.target.type==='checkbox'?e.target.checked:e.target.value;applySettings();save()}if(d.pref){state.preference=e.target.value;save()}});
applySettings();home();
